language: node_js

node_js: stable

addons:
  sonarcloud:
    organization: han-feng-github
    token:
      secure: $SONAR_CLOUD_TOKEN

cache:
  directories:
    - node_modules

script:
  - npm run build:travis
  - npm run test:unit

deploy:
  provider: pages
  local-dir: target/dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

after_success:
  - npx codecov --token=$CODECOV_TOKEN
  - sonar-scanner
